version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: my-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: